# Generated by Django 5.1.6 on 2025-03-05 06:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
